 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: "TF_PLAN"
  jobs:
  - job: "TF_init_build"
    steps:
    - script: |
        echo 'terraform init'
        terraform init
      displayName: "Run Terraform init"
    - script: |
        echo 'terraform plan'
        terraform plan -out plan.out
      displayName: "Run Terraform plan"
    - task: CopyFiles@2 
      inputs:
        SourceFolder: '$(Build.DefaultWorkingDirectory)'
        Contents: '**.out'
        TargetFolder: '$(Build.DefaultWorkingDirectory)/temp'
    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact"
      inputs:
        PathtoPublish: '$(Build.DefaultWorkingDirectory)/temp'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: "TF_APPLY"
  jobs:
  - job: "TF_run"
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - script:
        echo "terraform apply"
        terraform apply plan.out
      displayName: "Run Terraform apply"
      workingDirectory: $(System.ArtifactsDirectory)/drop

